-- MySQL Script generated by MySQL Workbench
-- Thu Jan 20 23:48:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estabelecimento` (
  `id` BIGINT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orgaoMaximo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orgaoMaximo` (
  `codigo` BIGINT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidadeGestora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidadeGestora` (
  `codigo` BIGINT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `orgao` BIGINT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK_orgao_idx` (`orgao` ASC) VISIBLE,
  CONSTRAINT `FK_orgao`
    FOREIGN KEY (`orgao`)
    REFERENCES `mydb`.`orgaoMaximo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`portador` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `unidadeGestora` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_unidadeGestora_Portador_idx` (`unidadeGestora` ASC) VISIBLE,
  CONSTRAINT `FK_unidadeGestora_Portador`
    FOREIGN KEY (`unidadeGestora`)
    REFERENCES `mydb`.`unidadeGestora` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transacao` (
  `id` BIGINT NOT NULL,
  `mesExtrato` DATE NULL,
  `dataTransacao` DATE NULL,
  `valorTransacao` DOUBLE NULL,
  `transacaocol` VARCHAR(45) NULL,
  `estabelecimento` BIGINT NULL,
  `unidadeGestora` BIGINT NULL,
  `portador` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_estabelecimento_idx` (`estabelecimento` ASC) VISIBLE,
  INDEX `FK_unidadeGestora_idx` (`unidadeGestora` ASC) VISIBLE,
  INDEX `FK_portador_idx` (`portador` ASC) VISIBLE,
  CONSTRAINT `FK_estabelecimento`
    FOREIGN KEY (`estabelecimento`)
    REFERENCES `mydb`.`estabelecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_unidadeGestora`
    FOREIGN KEY (`unidadeGestora`)
    REFERENCES `mydb`.`unidadeGestora` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_portador`
    FOREIGN KEY (`portador`)
    REFERENCES `mydb`.`portador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
